// web/src/components/AboutPage.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">About</div>

    <div class="content-text">
      <span
        >Hey, my name is Chris Meyers and I am a software engineer and
        technology enthusiast. Here are some things you should know about
        me:</span
      >

      <ul>
        <li>
          I studied computer science at
          <a class="fancytxt" href="https://www.rowan.edu">Rowan University</a>
          in Glassboro, NJ and earned a Bachelor of Science in Computer Science
        </li>
        <li ref="employment" v-if="employed">
          Currently, I am employed as a
          {{ mostRecentJob.title }} at
          <a class="fancytxt" :href="mostRecentJob.url">{{
            mostRecentJob.company
          }}</a>
        </li>
        <li>
          Some of my hobbies include:
          <ul>
            <li>
              <a class="fancytxt" href="https://www.goodreads.com/chrismeyers"
                >Reading</a
              >
            </li>
            <li>Photography</li>
            <li>
              <router-link class="fancytxt" to="/builds"
                >Building custom computers</router-link
              >
            </li>
            <li>Playing video games</li>
          </ul>
        </li>
        <li>
          I am the owner of this
          <a class="fancytxt" @click="showImage('clarkImg')">majestic beast</a>
        </li>
        <img
          v-img
          ref="clarkImg"
          alt="Clark the Corgi"
          src="/images/clark/DSC_1564-6.jpg"
          style="display: none"
        />
      </ul>

      <p>
        Over the years, I've gained experience with the following programming
        languages and frameworks:
      </p>

      <ul>
        <li>
          Desktop and CLI applications:
          <ul ref="desktop-languages">
            <li
              v-for="language in languages.desktop"
              :key="`${language}-desktop-li`"
            >
              {{ language }}
            </li>
          </ul>
        </li>
        <li>
          Websites, Web Apps, and APIs:
          <ul ref="web-languages">
            <li v-for="language in languages.web" :key="`${language}-web-li`">
              {{ language }}
            </li>
          </ul>
        </li>
      </ul>

      <span
        >As a professional software engineer, I strive to write clean, modular,
        and maintainable code. My primary goal is to create innovative and
        usable applications that solve problems. If you have any questions,
        comments, or would like to work together on a project, please
        <a
          class="fancytxt"
          :href="MAILTO_HREF"
          target="_blank"
          rel="noopener noreferrer"
          >send me a message</a
        >.</span
      >
    </div>
  </div>
</template>

<script>
import ResumeAPI from '@/utils/api/resume';
import ErrorsMixin from '@/mixins/Errors';
import { MAILTO_HREF } from '@/store/constants';

export default {
  name: 'about-page',
  mixins: [ErrorsMixin],
  data() {
    return {
      MAILTO_HREF,
      languages: {},
      mostRecentJob: {},
      employed: false,
    };
  },
  beforeRouteEnter(to, from, next) {
    ResumeAPI.getSummary()
      .then((summary) => next((vm) => vm.setData({ summary })))
      .catch((error) => next((vm) => vm.setData({ error })));
  },
  methods: {
    showImage(which) {
      const img = this.$refs[which];
      img.click();
    },
    setData({ summary = null, error = null }) {
      if (error) {
        this.handleCommonErrors(error);
      } else {
        this.languages = summary.data.languages;
        this.mostRecentJob = summary.data.mostRecentJob;
        this.employed = summary.data.mostRecentJob.employed;
      }
    },
  },
};
</script>

// packages/web/src/components/AboutPage.jsx
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import { useQuery } from '@tanstack/react-query';
import LightGallery from 'lightgallery/react';
import lgZoom from 'lightgallery/plugins/zoom';
import { hashCode } from '../utils';
import ResumeApi from '../utils/api/resume';
import {
  MAILTO_HREF,
  DEFAULT_DOCUMENT_TITLE,
  LIGHTGALLERY_LICENSE,
} from '../utils/constants';
import ToastMessage from './ToastMessage';
import Loading from './Loading';

const AboutPage = () => {
  document.title = DEFAULT_DOCUMENT_TITLE;

  const { isLoading, data, error } = useQuery(
    ['resume.summary'],
    ResumeApi.summary,
  );

  if (error) {
    toast.error(<ToastMessage title={error.title} message={error.message} />);
  }

  return (
    <div className="content">
      <div className="section-header section-header-size">
        <div>About</div>
      </div>

      <div className="content-text">
        {isLoading ? (
          <Loading lines={10} />
        ) : (
          <>
            <span>
              Hey, my name is Chris Meyers and I am a software engineer and
              technology enthusiast. Here are some things you should know about
              me:
            </span>

            <ul>
              <li>
                I studied computer science at{' '}
                <a className="fancytxt" href="https://www.rowan.edu">
                  Rowan University
                </a>{' '}
                in Glassboro, NJ and earned a Bachelor of Science in Computer
                Science
              </li>
              {data?.mostRecentJob?.employed && (
                <li data-testid="employment">
                  Currently, I am employed as a {data.mostRecentJob.title} at{' '}
                  <a href={data.mostRecentJob.url} className="fancytxt">
                    {data.mostRecentJob.company}
                  </a>
                </li>
              )}

              <li>
                Some of my hobbies include:
                <ul>
                  <li>
                    <a
                      className="fancytxt"
                      href="https://www.goodreads.com/chrismeyers"
                    >
                      Reading
                    </a>
                  </li>
                  <li>Photography</li>
                  <li>
                    <Link className="fancytxt" to="/builds">
                      Building custom computers
                    </Link>
                  </li>
                  <li>Chess</li>
                </ul>
              </li>
              <li>
                I am the owner of this{' '}
                <LightGallery
                  licenseKey={LIGHTGALLERY_LICENSE}
                  plugins={[lgZoom]}
                  elementClassNames="inline"
                >
                  <span
                    className="fancytxt"
                    data-src="/images/clark/DSC_1564-6.jpg"
                    data-sub-html="Clark the Corgi"
                  >
                    majestic beast
                  </span>
                </LightGallery>
              </li>
            </ul>

            <p>
              Over the years, I&apos;ve gained experience with the following
              programming languages and frameworks:
            </p>

            <ul>
              <li>
                Websites, web applications, and APIs:
                {data?.languages?.web && (
                  <ul data-testid="web-languages">
                    {data.languages.web.map((item) => (
                      <li key={`web-${hashCode(item)}`}>{item}</li>
                    ))}
                  </ul>
                )}
              </li>
              <li>
                Desktop and command-line interface (CLI) applications:
                {data?.languages?.desktop && (
                  <ul data-testid="desktop-languages">
                    {data.languages.desktop.map((item) => (
                      <li key={`desktop-${hashCode(item)}`}>{item}</li>
                    ))}
                  </ul>
                )}
              </li>
            </ul>

            <span>
              As a professional software engineer, I strive to write clean,
              modular, and maintainable code. My primary goal is to create
              innovative and usable applications that solve problems. If you
              have any questions, comments, or would like to work together on a
              project, please{' '}
              <a
                href={MAILTO_HREF}
                className="fancytxt"
                target="_blank"
                rel="noopener noreferrer"
              >
                send me a message
              </a>
              .
            </span>
          </>
        )}
      </div>
    </div>
  );
};

export default AboutPage;
