// web/src/components/About.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">About</div>

    <div class="content-text">
      <span>My name is Chris Meyers and I am a Software Engineer and technology enthusiast. Here's a quick list of things you should know about me:</span>

      <ul>
        <li>I studied Computer Science at <a class="fancytxt" href="https://www.rowan.edu/" target="_blank">Rowan University</a> in Glassboro, NJ and earned a Bachelor of Science in Computer Science.</li>
        <li>Currently, I am employed as a {{ currentJob ? currentJob.title : "" }} at <a class="fancytxt" :href="currentJob ? currentJob.url : ''" target="_blank">{{ currentJob ? currentJob.company : "" }}</a>.</li>
        <li>Some of my professional interests include:
          <ul>
            <li>Software Development, Web Development, Computer Networking</li>
          </ul>
        </li>
        <li>My hobbies include:
          <ul>
            <li>Photography, reading, <router-link class="fancytxt" to="/builds">building custom computers</router-link>, playing video games</li>
          </ul>
        </li>
        <li>I am the owner of this <a @click="openGallery(0)" class="fancytxt">majestic beast</a>.</li>
        <LightBox
          :images='[{"thumb": "/clark/DSC_1564-6.jpg", "src": "/clark/DSC_1564-6.jpg", "caption": "Clark the Corgi"}]'
          v-bind:ref="'lightbox-0'"
          :show-caption="true"
          :show-light-box="false"/>
      </ul>

      <p>Over the years, I've gained experience with the following programming languages and frameworks:</p>

      <ul>
        <li>Desktop and CLI applications:
          <ul>
            <li>{{ langMap ? langMap.desktop : "" }}</li>
          </ul>
        </li>
        <li>Websites, Web Apps, and APIs:
          <ul>
            <li>{{ langMap ? langMap.web : "" }}</li>
          </ul>
        </li>
      </ul>

      <span>I have spent my entire professional programming career striving to write clean, modular, and maintainable code. I am always up for the challenge of
      learning new languages and frameworks. If a language or framework that I'm unfamiliar with is the best choice for a project, I have no hesitation in
      breaking away from my comfort zones to explore new options. My primary goal is to create innovative and usable applications that solve problems.</span>

      <p><a href="mailto:chris@chrismeyers.info" class="fancytxt">Send me a message</a> if you have any questions, comments, or would like to work together on a project.</p>

    </div>
  </div>
</template>

<script>
import ResumeApi from "@/utils/api/resume"
import LightBox from '@/components/LightBox/LightBox'

export default {
  name: 'About',
  components: {
    LightBox
  },
  data() {
    return {
      langMap: null,
      currentJob: null
    }
  },
  mounted() {
    ResumeApi.getInfoForAboutPage().then(
      info => {
        this.langMap = info.langMap
        this.currentJob = info.currentJob
      }
    )
  },
  methods: {
    openGallery(id) {
      let lightbox = "lightbox-" + id
      this.$refs[lightbox].showImage(0)
    }
  }
}
</script>

// src/pages/About.jsx
import lgZoom from 'lightgallery/plugins/zoom';
import { Link } from 'react-router-dom';
import { summary } from '../assets/generated/resume';
import { createLightGallery } from '../components/Lightbox';
import Page from '../components/Page';
import { MAILTO_MESSAGE, SLOGAN } from '../constants';

const About = () => {
  document.title = SLOGAN;

  return (
    <Page header="About">
      <span>
        Hey, my name is Chris Meyers and I am a software engineer and technology
        enthusiast. Here are some things you should know about me:
      </span>

      <ul>
        <li>
          I studied computer science at{' '}
          <a className="fancytxt" href="https://www.rowan.edu">
            Rowan University
          </a>{' '}
          in Glassboro, NJ and earned a Bachelor of Science in Computer Science
        </li>
        {summary?.mostRecentJob?.employed && (
          <li data-testid="employment">
            Currently, I am employed as a {summary.mostRecentJob.title} at{' '}
            <a href={summary.mostRecentJob.url} className="fancytxt">
              {summary.mostRecentJob.company}
            </a>
          </li>
        )}

        <li>
          Some of my hobbies include:
          <ul>
            <li>
              <a
                className="fancytxt"
                href="https://www.goodreads.com/chrismeyers"
              >
                Reading
              </a>
            </li>
            <li>Photography</li>
            <li>
              <Link className="fancytxt" to="/builds">
                Building custom computers
              </Link>
            </li>
            <li>Chess</li>
          </ul>
        </li>
        <li>
          I am the owner of this{' '}
          {createLightGallery(
            [
              <span
                className="fancytxt"
                data-src="/images/clark/DSC_1564-6.jpg"
                data-sub-html="Clark the Corgi"
              >
                majestic beast
              </span>,
            ],
            {
              plugins: [lgZoom],
              elementClassNames: 'inline',
            }
          )}
        </li>
      </ul>

      <p>
        Over the years, I&apos;ve gained experience with the following
        programming languages and frameworks:
      </p>

      <ul>
        <li>
          Websites, web applications, and REST APIs:
          {summary?.languages?.web && (
            <ul data-testid="web-languages">
              {summary.languages.web.map((item) => (
                <li key={`web-${item}`}>{item}</li>
              ))}
            </ul>
          )}
        </li>
        <li>
          Desktop and command-line interface (CLI) applications:
          {summary?.languages?.desktop && (
            <ul data-testid="desktop-languages">
              {summary.languages.desktop.map((item) => (
                <li key={`desktop-${item}`}>{item}</li>
              ))}
            </ul>
          )}
        </li>
      </ul>

      <span>
        As a professional software engineer, I strive to write simple, modular,
        and maintainable code. My primary goal is to create innovative and
        usable applications that solve problems. If you have any questions,
        comments, or would like to work together on a project, please{' '}
        <a
          href={MAILTO_MESSAGE}
          className="fancytxt"
          target="_blank"
          rel="noopener noreferrer"
        >
          send me a message
        </a>
        .
      </span>
    </Page>
  );
};

export default About;
