// web/src/components/BuildPage.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">Build Details</div>

    <div class="content-text">
      <template v-if="error">
        <p class="center">
          Build
          <span>
            <pre class="highlighted">{{ $route.params.id }}</pre>
          </span>
          does not exist
        </p>
      </template>
      <template v-else-if="build">
        <div class="build" :key="build.id">
          <h2>{{ build.displayDate }}</h2>
          <div class="build-info">
            <div class="build-specs">
              <dl>
                <dt class="dt-mod"><b>CPU</b></dt>
                <dd>{{ build.cpu }}</dd>
                <template v-if="build.cool !== null">
                  <dt class="dt-mod"><b>Cooling</b></dt>
                  <dd>{{ build.cool }}</dd>
                </template>
                <dt class="dt-mod"><b>Motherboard</b></dt>
                <dd>{{ build.mobo }}</dd>
                <dt class="dt-mod"><b>RAM</b></dt>
                <dd>{{ build.ram }}</dd>
                <dt class="dt-mod"><b>HDD</b></dt>
                <dd>{{ build.hdd }}</dd>
                <template v-if="build.ssd !== null">
                  <dt class="dt-mod"><b>SSD</b></dt>
                  <dd>{{ build.ssd }}</dd>
                </template>
                <dt class="dt-mod"><b>GPU</b></dt>
                <dd>{{ build.gpu }}</dd>
              </dl>
            </div>
            <div v-if="build.image" class="build-pic">
              <img
                v-img
                v-if="build.image"
                :src="build.image.path"
                :class="`build-pic-img-${build.image.orient}`"
                :alt="build.image.title"
                title="Click to enlarge"
              />
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import BuildsAPI from '@/utils/api/builds';
import ErrorsMixin from '@/mixins/Errors';
import BuildsMixin from '@/mixins/Builds';
import { DEFAULT_DOCUMENT_TITLE } from '@/store/constants';

export default {
  name: 'build-page',
  mixins: [ErrorsMixin, BuildsMixin],
  data() {
    return {
      build: null,
      error: false,
    };
  },
  beforeRouteEnter(to, from, next) {
    BuildsAPI.getById(to.params.id)
      .then((build) => next((vm) => vm.setData({ build })))
      .catch((error) => next((vm) => vm.setData({ error })));
  },
  beforeRouteUpdate(to, from, next) {
    BuildsAPI.getById(to.params.id)
      .then((build) => this.setData({ build }))
      .catch((error) => this.setData({ error }))
      .finally(() => next());
  },
  methods: {
    setData({ build = null, error = null }) {
      if (error) {
        if ([400, 404].includes(error.statusCode)) {
          this.error = true;
        } else {
          this.handleCommonErrors(error);
        }
      } else {
        this.build = build.data;
        this.error = false;
        this.updateDocumentTitle();
      }
    },
    updateDocumentTitle() {
      const cpu = this.cleanCPU(this.build.cpu);
      document.title = `Build Details - ${cpu} - ${DEFAULT_DOCUMENT_TITLE}`;
    },
  },
};
</script>

<style scoped>
.content-text {
  max-width: 1000px;
}

.build {
  margin-bottom: 10px;
}

.build-info {
  margin: 10px;
  padding: 0;
}

.build-pic:hover {
  cursor: pointer;
}

.build-pic-img-land,
.build-pic-img-port {
  border-style: solid;
  border-width: 1px;
  border-color: #707070;
}

@media screen and (min-width: 970px) {
  .build-info {
    display: -webkit-flex;
    display: flex;
  }

  .build-specs {
    -webkit-flex: 3;
    flex: 3;
    padding-right: 20px;
  }

  .build-pic {
    -webkit-flex: 2;
    flex: 2;
  }

  .build-pic-img-land {
    max-width: 100%;
  }

  .build-pic-img-port {
    max-width: 100%;
  }
}

@media screen and (max-width: 969px) {
  .build-info {
    -webkit-flex-flow: column wrap;
    flex-flow: column wrap;
  }

  .build-pic {
    text-align: center;
  }

  .build-pic-img-land,
  .build-pic-img-port {
    height: 100%;
    width: 100%;
  }

  .build-pic-img-port {
    max-height: 525px;
    max-width: 406px;
  }
}

@media print {
  .build {
    page-break-after: always;
  }
  .build > h2 {
    margin-top: 50px;
  }

  .build-pic-img-land {
    height: 100%;
    width: 100%;
  }
  .build-pic-img-port {
    height: 60%;
    width: 60%;
  }
}
</style>

// web/src/components/BuildPage.jsx
import { Fragment, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { toast } from 'react-toastify';
import { SRLWrapper } from 'simple-react-lightbox';
import './css/build.css';
import BuildsAPI from '../utils/api/builds';
import { DEFAULT_DOCUMENT_TITLE } from '../utils/constants';
import ToastMessage from './ToastMessage';
import Loading from './Loading';

const BuildPage = () => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [build, setBuild] = useState({});

  const { id } = useParams();

  useEffect(() => {
    let isMounted = true;

    const fetchData = async () => {
      try {
        const response = await BuildsAPI.getById(id);
        if (isMounted) {
          document.title = `Build Details | ${response.data.displayDate} | ${DEFAULT_DOCUMENT_TITLE}`;
          setError(false);
          setBuild(response.data);
        }
      } catch (error) {
        document.title = `Build Details | ${id} | ${DEFAULT_DOCUMENT_TITLE}`;
        setError(true);
        toast.error(
          <ToastMessage title={error.title} message={error.message} />,
        );
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    };
    fetchData();

    return () => (isMounted = false);
  }, [id]);

  const buildDownloadFileName = () =>
    build.image.title
      .toLowerCase()
      .replaceAll("'", '') // eslint-disable-line quotes
      .replaceAll(' ', '-');

  return (
    <div className="content">
      <div className="section-header section-header-size">Build Details</div>

      <div className="content-text build">
        {loading ? (
          <Loading lines={10} header={true} />
        ) : (
          <>
            {error ? (
              <p className="center">
                Unable to load build{' '}
                <span className="pre highlighted">{id}</span>
              </p>
            ) : (
              <div className="build" key={build.id}>
                <h2>{build.displayDate}</h2>
                <div className="build-info">
                  <div className="build-specs">
                    <dl>
                      <dt className="dt-mod">
                        <b>CPU</b>
                      </dt>
                      <dd>{build.cpu}</dd>
                      {build.cool !== null && (
                        <>
                          <dt className="dt-mod">
                            <b>Cooling</b>
                          </dt>
                          <dd>{build.cool}</dd>
                        </>
                      )}
                      <dt className="dt-mod">
                        <b>Motherboard</b>
                      </dt>
                      <dd>{build.mobo}</dd>
                      <dt className="dt-mod">
                        <b>RAM</b>
                      </dt>
                      <dd>{build.ram}</dd>
                      <dt className="dt-mod">
                        <b>HDD</b>
                      </dt>
                      <dd>{build.hdd}</dd>
                      {build.ssd !== null && (
                        <>
                          <dt className="dt-mod">
                            <b>SSD</b>
                          </dt>
                          <dd>{build.ssd}</dd>
                        </>
                      )}
                      <dt className="dt-mod">
                        <b>GPU</b>
                      </dt>
                      <dd>{build.gpu}</dd>
                    </dl>
                  </div>
                  {build.image && (
                    <div className="build-pic">
                      <SRLWrapper
                        options={{
                          settings: {
                            downloadedFileName: buildDownloadFileName(),
                          },
                          buttons: {
                            showAutoplayButton: false,
                            showNextButton: false,
                            showPrevButton: false,
                          },
                          thumbnails: {
                            showThumbnails: false,
                          },
                        }}
                      >
                        <a href={build.image.path}>
                          <img
                            src={build.image.path}
                            className={`build-pic-img-${build.image.orient}`}
                            alt={build.image.title}
                            title="Click to enlarge"
                          />
                        </a>
                      </SRLWrapper>
                    </div>
                  )}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default BuildPage;
