// web/src/components/BuildsPage.jsx
import { Fragment, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'react-toastify';
import './css/builds.css';
import BuildsAPI from '../utils/api/builds';
import { DEFAULT_DOCUMENT_TITLE } from '../utils/constants';
import ToastMessage from './ToastMessage';
import Loading from './Loading';

const BuildsPage = () => {
  const [loading, setLoading] = useState(true);
  const [builds, setBuilds] = useState(null);

  useEffect(() => {
    let isMounted = true;

    document.title = `Builds | ${DEFAULT_DOCUMENT_TITLE}`;

    const fetchData = async () => {
      try {
        const response = await BuildsAPI.get();
        if (isMounted) {
          setBuilds(response.data.items);
        }
      } catch (error) {
        toast.error(
          <ToastMessage title={error.title} message={error.message} />,
        );
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    };
    fetchData();

    return () => (isMounted = false);
  }, []);

  const cleanCPU = (cpu) => {
    return cpu.split('@')[0].trim();
  };

  return (
    <div className="content">
      <div className="section-header section-header-size">Builds</div>

      <div className="content-text">
        {loading ? (
          <Loading lines={10} header={true} />
        ) : (
          <>
            {builds &&
              builds.map((build, index) => (
                <Fragment key={build.id}>
                  <div className="build" key="build.id">
                    <h2 className={index === 0 ? 'first-header' : ''}>
                      <Link
                        className="fancytxt"
                        title={`Click for details of ${build.displayDate}`}
                        to={`/builds/${build.id}`}
                      >
                        {build.displayDate}
                      </Link>
                    </h2>
                    <div className="build-overview">
                      <p>
                        An{' '}
                        <span className="highlighted">
                          {cleanCPU(build.cpu)}
                        </span>{' '}
                        based system
                      </p>
                      <p className="right">
                        <Link
                          className="subtle fancytxt"
                          title={`Click for details of ${build.displayDate}`}
                          to={`/builds/${build.id}`}
                        >
                          Build Details &gt;
                        </Link>
                      </p>
                    </div>
                  </div>

                  {index < builds.length - 1 && (
                    <>
                      <br />
                      <hr />
                    </>
                  )}
                </Fragment>
              ))}
          </>
        )}
      </div>
    </div>
  );
};

export default BuildsPage;

// web/src/components/BuildsPage.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">Builds</div>

    <div class="content-text">
      <template v-for="(build, index) in builds">
        <div class="build" :key="build.id" :id="`build-${build.id}`">
          <h2 :class="{ 'first-header': index == 0 }">
            <router-link
              :to="`/builds/${build.id}`"
              :title="`Click for details of ${build.displayDate}`"
              class="fancytxt"
              >{{ build.displayDate }}</router-link
            >
          </h2>
          <div class="build-overview">
            <p>
              An
              <span class="highlighted">{{ cleanCPU(build.cpu) }}</span>
              based system
            </p>
            <p class="right">
              <router-link
                :to="`/builds/${build.id}`"
                :title="`Click for details of ${build.displayDate}`"
                class="subtle fancytxt"
                >Build Details &gt;</router-link
              >
            </p>
          </div>
        </div>
        <template v-if="index < builds.length - 1">
          <br :key="`${build.id}-br`" />
          <hr :key="`${build.id}-hr`" />
        </template>
      </template>
    </div>
  </div>
</template>

<script>
import BuildsAPI from '@/utils/api/builds';
import ErrorsMixin from '@/mixins/Errors';

export default {
  name: 'builds-page',
  mixins: [ErrorsMixin],
  data() {
    return {
      builds: null,
    };
  },
  beforeRouteEnter(to, from, next) {
    BuildsAPI.get()
      .then((builds) => next((vm) => vm.setData({ builds })))
      .catch((error) => next((vm) => vm.setData({ error })));
  },
  methods: {
    setData({ builds = null, error = null }) {
      if (error) {
        this.handleCommonErrors(error);
      } else {
        this.builds = builds.data.items;
      }
    },
    cleanCPU(cpu) {
      return cpu.split('@')[0].trim();
    },
  },
};
</script>

<style scoped>
.build {
  margin-bottom: 10px;
}

.build-overview {
  margin-left: 40px;
}
</style>
