// src/components/Footer.jsx
import { useContext } from 'react';
import Switch from 'react-switch';
import PropTypes from 'prop-types';
import { ReactComponent as GithubIcon } from '../assets/images/icons/github.svg';
import { ReactComponent as LinkedInIcon } from '../assets/images/icons/linkedin.svg';
import { ReactComponent as MailIcon } from '../assets/images/icons/mail.svg';
import { ReactComponent as SunIcon } from '../assets/images/icons/sun.svg';
import { ReactComponent as MoonIcon } from '../assets/images/icons/moon.svg';
import {
  GITHUB_URL,
  LINKEDIN_URL,
  MAILTO_HREF,
  THEMES,
} from '../utils/constants';
import styles from '../styles/Footer.module.css';
import { ThemeContext } from '../context/ThemeContext';

const Footer = ({ inMenu }) => {
  const { theme, toggleTheme, mainThemeColor, lightModeToggleColor } =
    useContext(ThemeContext);

  return (
    <footer className={inMenu ? styles.inMenu : ''}>
      <div className={styles.links}>
        <div className={styles.social}>
          <a href={GITHUB_URL} className="no-decoration">
            <GithubIcon
              className="link-image large"
              title="GitHub"
              alt="Find me on GitHub"
            />
          </a>
        </div>

        <div className={styles.bullets}>&bull;</div>

        <div className={styles.social}>
          <a href={LINKEDIN_URL} className="no-decoration">
            <LinkedInIcon
              className="link-image large"
              title="LinkedIn"
              alt="Connect with me on LinkedIn"
            />
          </a>
        </div>

        <div className={styles.bullets}>&bull;</div>

        <div className={styles.social}>
          <a
            href={MAILTO_HREF}
            title="Send Message"
            target="_blank"
            rel="noopener noreferrer"
          >
            <MailIcon className="link-image large" alt="Send Message" />
          </a>
        </div>

        <div className={styles.bullets}>&bull;</div>

        <div className={styles.theme}>
          <Switch
            onChange={toggleTheme}
            checked={theme === THEMES.dark}
            onColor={mainThemeColor}
            offColor={lightModeToggleColor}
            aria-label="Toggle site theme"
            height={20}
            width={48}
            checkedIcon={<MoonIcon className="link-image small theme on" />}
            uncheckedIcon={<SunIcon className="link-image small theme off" />}
          />
        </div>
      </div>

      <span className={styles.years}>
        Designed and Developed by Chris Meyers, 2013-{new Date().getFullYear()}
      </span>
    </footer>
  );
};

Footer.defaultProps = {
  inMenu: false,
};

Footer.propTypes = {
  inMenu: PropTypes.bool,
};

export default Footer;

// web/src/components/Footer.vue
<template>
  <footer>
    <div class="footer-links">
      <div class="footer-social">
        <a href="https://github.com/chrismeyers"
           target="_blank"
           style="text-decoration: none;">
          <svgicon name="github" class="link-image large" alt="Find me on GitHub" title="GitHub"></svgicon>
        </a>
      </div>

      <div class="footer-bullets">&bull;</div>

     <div class="footer-social">
        <a href="https://www.linkedin.com/in/chris-meyers"
           target="_blank"
           style="text-decoration: none;">
          <svgicon name="linkedin" class="link-image large" alt="Connect with me on LinkedIn" title="LinkedIn"></svgicon>
        </a>
      </div>

      <div class="footer-bullets">&bull;</div>

      <div class="footer-social">
        <a v-tooltip="copyMessageOptions"
           alt="Send Message"
           style="cursor: pointer;"
           v-clipboard:copy="email"
           v-clipboard:success="onCopyEmail"
           @mouseleave="resetCopyMessage">
          <svgicon name="mail" class="link-image large"></svgicon>
        </a>
      </div>

      <div class="footer-bullets">&bull;</div>

      <div class="footer-theme">
        <toggle-button
          :value="$store.state.theme === THEMES.DARK"
          :labels="{checked: THEMES.DARK, unchecked: THEMES.LIGHT}"
          :width="55"
          :color="{checked: mainThemeColor}"
          :sync="true"
          @change="$store.commit('toggleTheme')" />
      </div>
    </div>

    <span class="footer-years">Designed and Developed by Chris Meyers, 2013-{{ new Date().getFullYear() }}</span>
  </footer>
</template>

<script>
import EmailTooltipMixin from "@/mixins/EmailTooltip"
import "@/assets/images/icons/generated/github"
import "@/assets/images/icons/generated/linkedin"
import "@/assets/images/icons/generated/mail"
import { THEMES } from "@/store/constants"

export default {
  name: "Footer",
  mixins: [EmailTooltipMixin],
  data() {
    return {
      THEMES: THEMES
    }
  },
  computed: {
    mainThemeColor: function() {
      return getComputedStyle(document.documentElement).getPropertyValue('--main-theme-color')
    }
  }
}
</script>

<style scoped>
footer {
  font-size: 13px;
  bottom: 0;
  height: auto;
  left: 0;
  right: 0;
  border-top: 1px solid var(--border-color);
  width: 300px;
  position: fixed;
  text-align: center;
}

.footer-links {
  display: block;
  text-align: center;
  margin-bottom: 5px;
  padding-right: 10px;
  padding-left: 10px;
  padding-top: 10px;
}

.footer-years {
  display: block;
  text-align: center;
  padding-right: 10px;
  padding-left: 10px;
  padding-bottom: 10px;
}

.footer-social {
  margin: 0px 3px;
}

.footer-social, .footer-bullets, .footer-message, .footer-theme {
  display: inline-block;
  vertical-align: middle;
  margin-left: 5px;
}

@media screen and (max-width: 969px) {
  footer {
    width: 100%;
    position: absolute;
  }
}
</style>
