// web2/src/components/NotFoundPage.jsx
import { Link, useLocation } from 'react-router-dom';

const NotFoundPage = () => {
  const location = useLocation();

  return (
    <div className="content">
      <div className="section-header section-header-size">Page Not Found</div>

      <div className="content-text">
        <p className="center">
          The path{' '}
          <span>
            {' '}
            <pre className="highlighted">{location.pathname}</pre>{' '}
          </span>{' '}
          does not exist
        </p>
        <p className="center">
          Go back{' '}
          <Link className="fancytxt" to="/">
            home
          </Link>
          !
        </p>
      </div>
    </div>
  );
};

export default NotFoundPage;

// web/src/components/NotFoundPage.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">404 Page Not Found</div>

    <div class="content-text">
      <p class="center">
        The path
        <span>
          <pre class="highlighted">{{ path }}</pre>
        </span>
        does not exist
      </p>
      <p class="center">
        Go back <router-link class="fancytxt" to="/">home</router-link>!
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'not-found-page',
  data() {
    return {
      path: '',
    };
  },
  beforeRouteEnter(to, from, next) {
    next((vm) => vm.setPath(to.path));
  },
  methods: {
    setPath(path) {
      this.path = path;
    },
  },
};
</script>
