// web/src/components/ProjectPage.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">Project Details</div>

    <div class="content-text">
      <template v-if="error">
        <p class="center">
          Project
          <span>
            <pre class="highlighted">{{ $route.params.id }}</pre>
          </span>
          does not exist
        </p>
      </template>
      <template v-else-if="project">
        <div class="project" :key="project.id">
          <h2>{{ project.title }}</h2>
          <h3>{{ project.displayDate }}</h3>
          <div class="project-wrapper">
            <div class="project-description">
              <dl>
                <dt class="dt-mod"><b>Language(s)</b></dt>
                <dd v-html="project.lang"></dd>

                <dt class="dt-mod"><b>Description</b></dt>
                <dd v-html="project.info"></dd>

                <dt class="dt-mod"><b>My Role</b></dt>
                <dd>{{ project.role }}</dd>

                <dt class="dt-mod"><b>Status</b></dt>
                <dd>{{ project.stat }}</dd>

                <dt class="dt-mod dt-links"><b>Links</b></dt>
                <dd v-if="project.webUrl !== null" class="project-link-image">
                  <svgicon
                    name="link-external"
                    class="link-image small"
                  ></svgicon
                  >&nbsp;<a :href="project.webUrl" class="fancytxt">Website</a>
                </dd>
                <dd class="project-link-image">
                  <svgicon name="github" class="link-image small"></svgicon
                  >&nbsp;<a :href="project.codeUrl" class="fancytxt">Code</a>
                </dd>
              </dl>
            </div>

            <div v-if="project.images.length > 0" class="project-images">
              <template v-for="(image, index) in project.images">
                <template v-if="index == 0">
                  <template v-if="image.path.toLowerCase().endsWith('.gif')">
                    <img
                      v-img
                      :src="image.path"
                      :alt="image.title"
                      :key="`${image.id}-full`"
                      :ref="`project-${project.id}-${index}-gif`"
                      style="display: none"
                    />
                    <template v-if="image.thumbnail">
                      <div
                        class="gif-overlay"
                        :key="`${image.id}-gif-thumbnail-wrapper`"
                        title="Play GIF"
                      >
                        <img
                          :src="image.thumbnail"
                          :class="`project-images-full-img-${image.orient}`"
                          :key="`${image.id}-gif-thumbnail`"
                          @click="showGIF(`project-${project.id}-${index}-gif`)"
                        />
                        <svgicon
                          name="play"
                          class="link-image xlarge play-overlay"
                          alt="Plays the associated GIF"
                          title="Play GIF"
                          :key="`${image.id}-gif-thumbnail-play`"
                        ></svgicon>
                      </div>
                    </template>
                    <template v-else>
                      <div
                        class="project-images-full-img-land project-images-gif"
                        :key="`${image.id}-missing-gif-thumbnail`"
                        @click="showGIF(`project-${project.id}-${index}-gif`)"
                      >
                        <svgicon
                          name="play"
                          class="link-image xlarge"
                          alt="Plays the associated GIF"
                          title="Play GIF"
                        ></svgicon>
                        <div>Play GIF</div>
                      </div>
                    </template>
                  </template>
                  <template v-else>
                    <img
                      v-img="{ group: project.id }"
                      :src="image.path"
                      :class="`project-images-full-img-${image.orient}`"
                      :alt="image.title"
                      :key="`${image.id}-full`"
                      title="Click to enlarge"
                    />
                  </template>
                  <br :key="`${image.id}-br`" />
                </template>
                <div
                  v-else
                  class="project-images-small"
                  :key="`${image.id}-small`"
                >
                  <img
                    v-img="{ group: project.id }"
                    :src="image.path"
                    :class="`project-images-small-img-${image.orient}`"
                    :alt="image.title"
                    title="Click to enlarge"
                  />
                </div>
              </template>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import ProjectsAPI from '@/utils/api/projects';
import ErrorsMixin from '@/mixins/Errors';
import '@/assets/images/icons/generated/github';
import '@/assets/images/icons/generated/link-external';
import '@/assets/images/icons/generated/play';
import { DEFAULT_DOCUMENT_TITLE } from '@/store/constants';

export default {
  name: 'project-page',
  mixins: [ErrorsMixin],
  data() {
    return {
      project: null,
      error: false,
    };
  },
  async beforeRouteEnter(to, from, next) {
    try {
      const project = await ProjectsAPI.getById(to.params.id);
      next((vm) => vm.setData({ project }));
    } catch (error) {
      next((vm) => vm.setData({ error }));
    }
  },
  async beforeRouteUpdate(to, from, next) {
    try {
      const project = await ProjectsAPI.getById(to.params.id);
      this.setData({ project });
    } catch (error) {
      this.setData({ error });
    } finally {
      next();
    }
  },
  methods: {
    setData({ project = null, error = null }) {
      if (error) {
        if ([400, 404].includes(error.statusCode)) {
          this.error = true;
        } else {
          this.handleCommonErrors(error);
        }
      } else {
        this.project = project.data;
        this.error = false;
        this.updateDocumentTitle();
      }
    },
    updateDocumentTitle() {
      document.title = `Project Details | ${this.project.title} | ${DEFAULT_DOCUMENT_TITLE}`;
    },
    showGIF(which) {
      const gif = this.$refs[which][0];

      gif.click();

      // Restart the GIF each time it's opened
      setTimeout(() => {
        const img = document.querySelectorAll('.content-v-img > img')[0];
        img.src = gif.src;
      }, 100);
    },
  },
};
</script>

<style scoped>
.content-text {
  max-width: 1000px;
}

.project-link-image {
  margin-bottom: 10px;
}

.project {
  height: auto;
}

.project-wrapper {
  margin: 10px;
  padding: 0;
}

.project-images > img,
.project-images > div,
.project-images-small > img {
  cursor: pointer;
}

.project-images-small {
  display: inline-block;
  margin-right: 4px;
}

.project-images-small-img-square {
  height: 44px;
  width: 44px;
  border-style: solid;
  border-width: 1px;
  border-color: #707070;
}

.project-images-small-img-port {
  height: 50px;
  width: 25px;
  border-style: solid;
  border-width: 1px;
  border-color: #707070;
}

.project-images-small-img-land {
  height: 25px;
  width: 60px;
  border-style: solid;
  border-width: 1px;
  border-color: #707070;
}

.project-images-full-img-square,
.project-images-full-img-land,
.project-images-full-img-port {
  border-style: solid;
  border-width: 1px;
  border-color: #707070;
}

.project-images-gif {
  display: flex;
  width: 100%;
  height: 100%;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  border-style: none;
}

.link-image.play-overlay {
  position: absolute;
  pointer-events: none;
}

.gif-overlay {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
}

@media screen and (min-width: 970px) {
  .project-wrapper {
    display: -webkit-flex;
    display: flex;
  }

  .project-description {
    -webkit-flex: 3;
    flex: 3;
  }

  .project-images {
    -webkit-flex: 2;
    flex: 2;
    padding-left: 20px;
  }

  .project-images-full-img-square {
    max-width: 100%;
  }

  .project-images-full-img-land {
    max-width: 100%;
  }

  .project-images-full-img-port {
    max-width: 100%;
  }
}

@media screen and (max-width: 969px) {
  .project-wrapper {
    -webkit-flex-flow: column wrap;
    flex-flow: column wrap;
  }

  .project-images {
    text-align: center;
  }

  .project-images-full-img-square,
  .project-images-full-img-land,
  .project-images-full-img-port {
    height: 100%;
    width: 100%;
  }

  .project-images-full-img-square {
    max-width: 415px;
    max-width: 415px;
  }

  .project-images-small {
    text-decoration: none;
  }
}

@media print {
  .project,
  .project-images {
    page-break-after: always;
  }
  .project > h2 {
    margin-top: 50px;
  }

  .project-images-full-img-square,
  .project-images-full-img-land,
  .project-images-full-img-port {
    margin-top: 0;
    height: 80%;
    width: 80%;
  }

  .project-images-small {
    display: inline;
  }

  .project-images-small-img-square {
    height: 200px;
    width: 200px;
    margin-right: 20px;
  }
  .project-images-small-img-land {
    height: 40%;
    width: 40%;
    margin-right: 20px;
  }
  .project-images-small-img-port {
    height: 25%;
    width: 25%;
    margin-right: 20px;
  }

  .project-link {
    width: 16px;
    height: 16px;
  }
}
</style>

// web/src/components/ProjectPage.jsx
import { Fragment, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { toast } from 'react-toastify';
import { SRLWrapper } from 'simple-react-lightbox';
import './css/project.css';
import { ReactComponent as ExternalLinkIcon } from '../assets/images/icons/link-external.svg';
import { ReactComponent as GithubIcon } from '../assets/images/icons/github.svg';
import { ReactComponent as PlayIcon } from '../assets/images/icons/play.svg';
import ProjectsAPI from '../utils/api/projects';
import { DEFAULT_DOCUMENT_TITLE } from '../utils/constants';
import ToastMessage from './ToastMessage';
import Loading from './Loading';

const ProjectPage = () => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [project, setProject] = useState({});

  const { id } = useParams();

  useEffect(() => {
    let isMounted = true;

    const fetchData = async () => {
      try {
        const response = await ProjectsAPI.getById(id);
        if (isMounted) {
          document.title = `Project Details | ${response.data.title} | ${DEFAULT_DOCUMENT_TITLE}`;
          setError(false);
          setProject(response.data);
        }
      } catch (error) {
        document.title = `Project Details | ${id} | ${DEFAULT_DOCUMENT_TITLE}`;
        setError(true);
        toast.error(
          <ToastMessage title={error.title} message={error.message} />,
        );
      } finally {
        if (isMounted) {
          setLoading(false);
        }
      }
    };
    fetchData();

    return () => (isMounted = false);
  }, [id]);

  const buildDownloadFileName = () =>
    project.title.toLowerCase().replaceAll(' ', '-');

  const restartGIF = () => {
    // Restart the GIF each time it's opened
    setTimeout(() => {
      const gif = document.getElementsByClassName('SRLImage')[0];

      if (gif) {
        document.getElementsByClassName('SRLImage')[0].src = gif.src;
      }
    }, 100);
  };

  return (
    <div className="content">
      <div className="section-header section-header-size">
        <div className={loading ? 'section-header-loading' : ''}>
          {loading ? <Loading lines={0} header={true} /> : 'Project Details'}
        </div>
      </div>

      <div className="content-text project">
        {loading ? (
          <Loading lines={10} header={true} />
        ) : (
          <>
            {error ? (
              <p className="center">
                Unable to load project{' '}
                <span className="pre highlighted">{id}</span>
              </p>
            ) : (
              <div className="project" key={project.id}>
                <h2>{project.title}</h2>
                <h3>{project.displayDate}</h3>
                <div className="project-wrapper">
                  <div className="project-description">
                    <dl>
                      <dt className="dt-mod">
                        <b>Language(s)</b>
                      </dt>
                      <dd
                        dangerouslySetInnerHTML={{ __html: project.lang }}
                      ></dd>

                      <dt className="dt-mod">
                        <b>Description</b>
                      </dt>
                      <dd
                        dangerouslySetInnerHTML={{ __html: project.info }}
                      ></dd>

                      <dt className="dt-mod">
                        <b>My Role</b>
                      </dt>
                      <dd>{project.role}</dd>

                      <dt className="dt-mod">
                        <b>Status</b>
                      </dt>
                      <dd>{project.stat}</dd>

                      <dt className="dt-mod dt-links">
                        <b>Links</b>
                      </dt>
                      {project.webUrl !== null && (
                        <dd className="project-link-image">
                          <ExternalLinkIcon
                            className="link-image small"
                            title="External website"
                            alt="Link to external website"
                          />{' '}
                          <a href={project.webUrl} className="fancytxt">
                            Website
                          </a>
                        </dd>
                      )}
                      <dd className="project-link-image">
                        <GithubIcon
                          className="link-image small"
                          title="GitHub repository"
                          alt="Link to GitHub repository"
                        />{' '}
                        <a href={project.codeUrl} className="fancytxt">
                          Code
                        </a>
                      </dd>
                    </dl>
                  </div>

                  {project.images && project.images.length > 0 && (
                    <div className="project-images">
                      {project.images[0].path.toLowerCase().endsWith('.gif') ? (
                        <SRLWrapper
                          callbacks={{
                            onLightboxOpened: () => restartGIF(),
                          }}
                          options={{
                            settings: {
                              downloadedFileName: buildDownloadFileName(),
                            },
                            thumbnails: {
                              showThumbnails: false,
                            },
                          }}
                        >
                          {project.images.map((image, index) => (
                            <Fragment key={image.id}>
                              <div className="gif-overlay" title="Play GIF">
                                <a href={image.path}>
                                  <img
                                    src={image.thumbnail}
                                    className={`project-images-full-img-${image.orient}`}
                                    alt={image.title}
                                    title="Click to enlarge"
                                  />
                                </a>
                                <PlayIcon
                                  name="play"
                                  className="link-image xlarge play-overlay"
                                  alt="Plays the associated GIF"
                                  title="Play GIF"
                                />
                              </div>
                            </Fragment>
                          ))}
                        </SRLWrapper>
                      ) : (
                        <SRLWrapper
                          options={{
                            settings: {
                              downloadedFileName: buildDownloadFileName(),
                            },
                          }}
                        >
                          {project.images.map((image, index) => (
                            <Fragment key={image.id}>
                              {index === 0 ? (
                                <a href={image.path}>
                                  <img
                                    src={image.path}
                                    className={`project-images-full-img-${image.orient}`}
                                    alt={image.title}
                                    title="Click to enlarge"
                                  />
                                </a>
                              ) : (
                                <div className="project-images-small">
                                  <a href={image.path}>
                                    <img
                                      src={image.path}
                                      className={`project-images-small-img-${image.orient}`}
                                      alt={image.title}
                                      title="Click to enlarge"
                                    />
                                  </a>
                                </div>
                              )}
                            </Fragment>
                          ))}
                        </SRLWrapper>
                      )}
                    </div>
                  )}
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default ProjectPage;
