// src/components/Prompt.jsx
import { useEffect, useState, useCallback, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { themePropTypes } from '../hooks/useTheme';
import { THEMES } from '../utils/constants';
import styles from '../styles/Prompt.module.css';

let CONSOLE_MESSAGE_DISPLAYED = false;

const Prompt = ({ theme }) => {
  const [promptVisible, setPromptVisible] = useState(false);
  const [outputWindowVisible, setOutputWindowVisible] = useState(false);
  const [arrowDirection, setArrowDirection] = useState('up');
  const [history, setHistory] = useState([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  const [output, setOutput] = useState('');
  const [command, setCommand] = useState('');

  const outputWindowRef = useRef(null);
  const promptRef = useRef(null);

  const navigate = useNavigate();
  const location = useLocation();

  const ARROWS = {
    up: '&#9650;',
    down: '&#9660;',
  };

  const scrollOutputWindowToTop = useCallback(() => {
    if (outputWindowRef.current) {
      outputWindowRef.current.scrollTop = 0;
    }
  }, []);

  const scrollOutputWindowToBottom = useCallback(() => {
    if (outputWindowRef.current) {
      outputWindowRef.current.scrollTop = outputWindowRef.current.scrollHeight;
    }
  }, []);

  const showOutputWindow = useCallback(
    ({ top = false, bottom = false }) => {
      setOutputWindowVisible(true);
      setArrowDirection('down');
      if (top) setTimeout(() => scrollOutputWindowToTop(), 0);
      if (bottom) setTimeout(() => scrollOutputWindowToBottom(), 0);
    },
    [scrollOutputWindowToBottom, scrollOutputWindowToTop]
  );

  const hideOutputWindow = () => {
    setOutputWindowVisible(false);
    setArrowDirection('up');
  };

  const showPrompt = () => {
    setPromptVisible(true);
  };

  const clearCommand = () => {
    setCommand('');
  };

  const clearOutput = () => {
    setOutput('');
  };

  const hidePrompt = useCallback(() => {
    setPromptVisible(false);
    setHistoryIndex(-1);
    hideOutputWindow();
    clearCommand();
  }, []);

  const toggleOutputWindow = useCallback(() => {
    return outputWindowVisible
      ? hideOutputWindow()
      : showOutputWindow({ bottom: true });
  }, [outputWindowVisible, showOutputWindow]);

  const setTheme = useCallback(
    (which) => {
      theme.applyTheme(which);
    },
    [theme]
  );

  const moveCursorToEnd = () => {
    promptRef.current.selectionStart = promptRef.current.value.length;
    promptRef.current.selectionEnd = promptRef.current.value.length;
  };

  useEffect(() => {
    if (history[historyIndex] === undefined) {
      clearCommand();
    } else {
      setCommand(history[historyIndex]);
    }
  }, [history, historyIndex]);

  const prev = useCallback(() => {
    if (historyIndex < history.length - 1) {
      setHistoryIndex((currentHistoryIndex) => currentHistoryIndex + 1);
    }
    moveCursorToEnd();
  }, [history.length, historyIndex]);

  const next = useCallback(() => {
    if (historyIndex >= 0) {
      setHistoryIndex((currentHistoryIndex) => currentHistoryIndex - 1);
    }
    moveCursorToEnd();
  }, [historyIndex]);

  const echo = useCallback(
    (args) => {
      clearOutput();
      setOutput(args.join(' '));
      showOutputWindow({ top: true });
    },
    [showOutputWindow]
  );

  const cd = useCallback(
    (args) => {
      let path = args[0];
      if (args.length < 1) {
        path = '';
      }
      if (path.startsWith('/')) {
        path = path.substring(1);
      }
      if (path.endsWith('/')) {
        path = path.slice(0, -1);
      }

      path = `/${path}`;

      if (location.pathname === path) {
        return;
      }

      navigate(path);
    },
    [location.pathname, navigate]
  );

  const exit = useCallback(() => {
    hidePrompt();
  }, [hidePrompt]);

  const help = useCallback(() => {
    clearOutput();

    const siteThemes = Object.values(THEMES).reduce(
      (acc, cur) => `${acc}, ${cur}`
    );

    // prettier-ignore
    setOutput(`usage: command [arg1] [arg2] ...
  Available commands:
  echo   - prints args to the output window
  cd     - navigates to the given arg
  toggle - toggles the output window
  theme  - sets the website theme to the arg
           themes: ${siteThemes}
           e.g. theme ${Object.values(THEMES)[0]}
  exit   - closes the command prompt
  help   - prints this message
  `);

    showOutputWindow({ top: true });
  }, [showOutputWindow]);

  const run = useCallback(
    ({ cmd = null, recordHistory = true }) => {
      if (cmd === '') return;

      if (recordHistory) {
        // Push to top of history stack
        setHistory((prevHistory) => [cmd, ...prevHistory]);
      }

      const parts = cmd
        .split(' ')
        .filter((p) => {
          return p !== '';
        })
        .map((p) => p.trim());
      const cleanedCommand = parts[0].trim().toLowerCase();
      const args = parts.slice(1);

      switch (cleanedCommand) {
        case 'echo':
          echo(args);
          break;
        case 'cd':
          cd(args);
          break;
        case 'toggle':
          toggleOutputWindow();
          break;
        case 'theme':
          setTheme(args[0]);
          break;
        case 'exit':
          exit();
          break;
        case 'help':
          help();
          break;
        default:
          break;
      }

      setHistoryIndex(-1);
      clearCommand();
    },
    [cd, echo, exit, help, setTheme, toggleOutputWindow]
  );

  useEffect(() => {
    if (
      history.length > 0 &&
      ['help', 'echo'].includes(history[0].split(' ')[0])
    ) {
      return;
    }

    const gutter = history.length.toString().length + 1;
    const historyString = history
      .slice()
      .reverse()
      .reduce(
        (acc, cur, i) =>
          `${acc}${(i + 1).toString().padStart(gutter, ' ')} ${cur} \n`,
        ''
      );

    setOutput(historyString);

    setTimeout(() => scrollOutputWindowToBottom(), 0);
  }, [history, scrollOutputWindowToBottom]);

  useEffect(() => {
    const keyupFn = (e) => {
      if (e.code === 'Backquote') {
        e.preventDefault(); // Prevents adding ` when opening the prompt
        showPrompt();
      } else if (e.code === 'Escape') {
        hidePrompt();
      } else if (e.code === 'Enter') {
        if (promptVisible) {
          run({ cmd: command, event: e });
        }
      } else if (e.code === 'ArrowUp') {
        if (promptVisible) {
          prev();
        }
      } else if (e.code === 'ArrowDown') {
        if (promptVisible) {
          next();
        }
      }
    };

    window.addEventListener('keyup', keyupFn);

    return () => window.removeEventListener('keyup', keyupFn);
  }, [command, hidePrompt, next, prev, promptVisible, run]);

  useEffect(() => {
    if (!CONSOLE_MESSAGE_DISPLAYED) {
      // eslint-disable-next-line no-console
      console.info(
        `%c[${window.location.host}] Prefer a CLI? Press the tilde (~) key when focused on the website and type \`help\` for usage.`,
        'font-size: 16px; background-color: rgba(0,0,0,0.85); color: #00CC00; font-family: "Courier New", Courier, monospace;'
      );

      CONSOLE_MESSAGE_DISPLAYED = true;
    }
  }, []);

  return (
    promptVisible && (
      <div className={styles.wrapper}>
        {outputWindowVisible && (
          <textarea
            value={output}
            className={`${styles.outputWindow} ${styles.hackerman}`}
            ref={outputWindowRef}
            readOnly="readonly"
          />
        )}
        <input
          className={`${styles.caret} ${styles.hackerman}`}
          value=">"
          maxLength="1"
          readOnly="readonly"
        />
        <input
          value={command}
          onChange={(e) => setCommand(e.target.value)}
          className={`${styles.prompt} ${styles.hackerman}`}
          ref={promptRef}
          maxLength="75"
          autoComplete="off"
          autoFocus // eslint-disable-line jsx-a11y/no-autofocus
        />
        <button
          type="button"
          aria-label="Toggle prompt output window"
          className={`${styles.outputWindowBtn} ${styles.hackerman}`}
          onClick={() => run({ cmd: 'toggle', recordHistory: false })}
          dangerouslySetInnerHTML={{ __html: ARROWS[arrowDirection] }} // eslint-disable-line react/no-danger
        />
      </div>
    )
  );
};

Prompt.propTypes = {
  theme: themePropTypes.isRequired,
};

export default Prompt;

// web/src/components/Prompt.vue
<template>
  <div v-show="promptVisible" id="prompt-div">
    <textarea v-if="textareaVisible" v-model="info" class="textarea-mod prompt-style" id="prompt-textarea" readonly="readonly"></textarea>
    <input class="input-mod prompt-style" id="prompt-caret" value=">" maxlength="1" readonly="readonly">
    <input v-model="command" ref="prompt" class="input-mod prompt-style" id="prompt" maxlength="75">
    <button class="prompt-style" id="prompt-textarea-btn" @click="run('toggle')" v-html="arrows[arrowDirection]"></button>
  </div>
</template>

<script>
import { THEMES } from "@/store/constants"

export default {
  name: "Prompt",
  data () {
    return {
      promptVisible: false,
      textareaVisible: false,
      arrows: {
        "up": "&#9650;",
        "down": "&#9660;"
      },
      arrowDirection: "up",
      command: "",
      info: "",
      history: [],
      historyIndex: -1
    }
  },
  mounted () {
    // eslint-disable-next-line no-console
    console.info(
      `%c[${window.location.host}] Hey, prefer a CLI? Press the tilde (~) key and type \`help\` for usage.`,
      "font-size: 16px; background-color: rgba(0,0,0,0.85); color: #00CC00; font-family: 'Courier New', Courier, monospace;"
    )

    window.addEventListener("keydown", e => {
      if (e.code === "Backquote") {
        e.preventDefault() // Prevents adding ` when opening the prompt
        this.showPrompt()
      } else if (e.code === "Escape") {
        this.hidePrompt()
      } else if (e.code === "Enter") {
        if (this.promptVisible) {
          this.run()
        }
      } else if (e.code === "ArrowUp") {
        if (this.promptVisible) {
          this.prev()
        }
      } else if (e.code === "ArrowDown") {
        if (this.promptVisible) {
          this.next()
        }
      }
    })
  },
  methods: {
    togglePrompt () {
      if (this.promptVisible) {
        this.hidePrompt()
      } else {
        this.showPrompt()
      }
    },
    showPrompt () {
      this.promptVisible = true
      this.focusPrompt()
    },
    hidePrompt () {
      this.promptVisible = false
      this.historyIndex = -1
      this.hideTextarea()
      this.clearCommand()
    },
    focusPrompt () {
      this.$nextTick(() => {
        this.$refs.prompt.focus()
      })
    },
    toggleTextarea () {
      if (this.textareaVisible) {
        this.hideTextarea()
      } else {
        this.showTextarea()
      }
    },
    showTextarea () {
      this.textareaVisible = true
      this.arrowDirection = "down"
    },
    hideTextarea () {
      this.textareaVisible = false
      this.arrowDirection = "up"
    },
    toggleTheme (which) {
      this.$store.commit("setTheme", which)
    },
    scrollTextareaToBottom () {
      let textarea = this.$el.querySelector("#prompt-textarea")
      textarea.scrollTop = textarea.scrollHeight
    },
    clearCommand () {
      this.command = ""
    },
    setCommand (cmd) {
      this.command = cmd
      // Force the model to update even if the adjacent command is the same
      // as the current command.
      this.$forceUpdate()
    },
    clearTextarea () {
      this.info = ""
    },
    moveCursorToEnd () {
      const pos = this.command.length

      // NOTE: this.$nextTick doesn't work here...
      setTimeout(() => {
        this.$refs.prompt.selectionStart = pos
        this.$refs.prompt.selectionEnd = pos
      }, 10)
    },
    prev () {
      if (this.historyIndex < this.history.length - 1) {
        this.historyIndex++
        this.setCommand(this.history[this.historyIndex])
      }

      this.moveCursorToEnd()
    },
    next () {
      if (this.historyIndex >= 0) {
        this.historyIndex--
        if (this.historyIndex < 0) {
          this.setCommand("")
        } else {
          this.setCommand(this.history[this.historyIndex])
        }
      }
    },
    run (command = null) {
      if (command) {
        // Only store user entered commands
        this.command = command
      } else {
        // Push to top of history stack
        this.history.unshift(this.command)
      }

      const parts = this.command.toLowerCase().split(" ").filter(p => {
        return p !== ""
      }).map(p => p.trim())
      const cmd = parts[0].trim()
      const args = parts.slice(1)
      let refreshHistory = true

      if (cmd === "echo") {
        this.echo(args)
      } else if (cmd === "cd") {
        this.cd(args)
      } else if (cmd === "login") {
        this.cd(["login"])
      } else if (cmd === "toggle") {
        this.toggleTextarea()
      } else if (cmd === "theme") {
        this.toggleTheme(args[0])
      } else if (cmd === "exit") {
        this.exit()
      } else if (cmd === "help") {
        this.help()
        refreshHistory = false
      }

      this.historyIndex = -1
      this.clearCommand()

      if (refreshHistory && this.textareaVisible) {
        this.printHistory()
      }
    },
    echo (args) {
      alert(args.join(" "))
    },
    cd (args) {
      let path = args[0]
      if (args.length < 1) {
        path = ""
      }

      this.$router.push({path: `/${path}`})
    },
    exit () {
      this.hidePrompt()
    },
    help () {
      this.clearTextarea()
      let themeList = Object.values(THEMES).reduce((acc, cur) => `${acc}, ${cur}`)
      this.info = `usage: command [arg1] [arg2] ...
Available commands:
  echo   - prints args to alert() box
  cd     - navigates to the given arg
  toggle - toggles the info box
  theme  - sets the theme to the arg (options: ${themeList})
  exit   - closes the command prompt
  help   - prints this message
`
      if (!this.textareaVisible) {
        this.showTextarea()
      }
    },
    printHistory () {
      this.clearTextarea()

      let gutter = this.history.length.toString().length + 1
      this.history.slice().reverse().forEach((item, i) => {
        this.info += `${(i + 1).toString().padStart(gutter, ' ')} ${item} \n`
      })

      if (!this.textareaVisible) {
        this.showTextarea()
      }

      this.$nextTick(() => {
        this.scrollTextareaToBottom()
      })
    },
  }
}
</script>

<style scoped>
.prompt-style {
  height: 25px;
  background-color: rgba(0,0,0,0.85);
  color: #00CC00;
  font-family: "Courier New", Courier, monospace;
  border: 0;
  font-weight: bold;
}

#prompt-div {
  bottom: 30px;
  margin-left: 310px;
  position: fixed;
}

#prompt-caret {
  width: 10px;
  font-weight: bold;
  padding-left: 5px;
  padding-right: 1px;
}
#prompt-caret:focus {
  outline: none;
}

#prompt {
  width: 500px;
  padding-left: 1px;
  padding-right: 1px;
}
#prompt:focus {
  outline: none;
}
#prompt::-ms-clear {
  width: 0px;
  height: 0px;
}

#prompt-textarea {
  width: 535px;
  padding: 2px;
  border: 0;
  resize: none;
  position: absolute;
  bottom: 30px;
  font-size: 12px;
  height: 150px;
}
#prompt-textarea:focus {
  outline: none;
}

#prompt-textarea-btn {
  border: 0;
  width: 21px;
  height: 27px;
  cursor: pointer;
}
#prompt-textarea-btn:focus {
  outline: none;
}

@media screen and (max-width: 969px) {
  #prompt-div {
    display: none;
  }
}
</style>
