// web2/src/components/ResumePage.jsx
import { Fragment, useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import './css/resume.css';
import ResumeApi from '../utils/api/resume';
import { RESUME_PDF_URL } from '../utils/constants';
import ToastMessage from './ToastMessage';
import Loading from './Loading';

const ResumePage = () => {
  const [loading, setLoading] = useState(true);
  const [experience, setExperience] = useState(null);
  const [education, setEducation] = useState(null);
  const [skills, setSkills] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await ResumeApi.get();
        setExperience(response.data.experience);
        setEducation(response.data.education);
        setSkills(response.data.skills);
      } catch (error) {
        toast.error(
          <ToastMessage title={error.title} message={error.message} />,
        );
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  return (
    <div className="content">
      <div className="section-header section-header-size">Résumé</div>

      {loading ? (
        <Loading />
      ) : (
        <div className="content-text">
          <h2 className="top">Experience</h2>
          {experience &&
            experience.map((job, i) => {
              return (
                <ul className="italic-spacer" key={`job-${i}`}>
                  <li className="left-column company" key={`job-company-${i}`}>
                    <a
                      className="fancytxt"
                      href={job.url}
                      dangerouslySetInnerHTML={{ __html: job.firstLine[0] }}
                    ></a>
                  </li>
                  <li
                    className="right-column location"
                    key={`job-location-${i}`}
                    dangerouslySetInnerHTML={{ __html: job.firstLine[1] }}
                  ></li>

                  {job.secondLine.map((secondLine, j) => {
                    return (
                      <Fragment key={`job-secondLine-${i}-${j}`}>
                        <li
                          className={`left-column sub-left-column job-title ${
                            j > 0 && job.info[j].length > 0
                              ? 'same-company-spacing'
                              : ''
                          }`}
                          key={`job-title-${i}-${j}`}
                          dangerouslySetInnerHTML={{ __html: secondLine[0] }}
                        ></li>
                        <li
                          className={`right-column tenure ${
                            j > 0 && job.info[j].length > 0
                              ? 'same-company-spacing'
                              : ''
                          }`}
                          key={`job-tenure-${i}-${j}`}
                          dangerouslySetInnerHTML={{ __html: secondLine[1] }}
                        ></li>

                        {job.info && job.info[j].length > 0 && (
                          <li
                            className="remove-bullets"
                            key={`job-info-${i}-${j}`}
                          >
                            <ul
                              className="more-info-wrapper"
                              key={`job-info-wrapper-${i}-${j}`}
                            >
                              {job.info[j].map((info, k) => {
                                return (
                                  <li
                                    className="more-info"
                                    key={`job-info-item-${i}-${j}-${k}`}
                                    dangerouslySetInnerHTML={{ __html: info }}
                                  ></li>
                                );
                              })}
                            </ul>
                          </li>
                        )}
                      </Fragment>
                    );
                  })}
                </ul>
              );
            })}

          <br />
          <hr />

          <h2>Education</h2>
          {education &&
            education.map((school, i) => {
              return (
                <ul className="italic-spacer" key={`school-${i}`}>
                  <li
                    className="left-column degree"
                    key={`school-degree-${i}`}
                    dangerouslySetInnerHTML={{ __html: school.firstLine[0] }}
                  ></li>
                  <li
                    className="right-column location"
                    key={`school-location-${i}`}
                    dangerouslySetInnerHTML={{ __html: school.firstLine[1] }}
                  ></li>
                  {school.secondLine.map((secondLine, j) => {
                    return (
                      <Fragment key={`school-secondLine-${i}-${j}`}>
                        <li
                          className="left-column sub-left-column school"
                          key={`school-school-${i}-${j}`}
                        >
                          <a
                            className="fancytxt"
                            key={`school-company-link-${i}-${j}`}
                            href={school.url}
                            dangerouslySetInnerHTML={{ __html: secondLine[0] }}
                          ></a>
                        </li>
                        <li
                          className="right-column tenure"
                          key={`school-tenure-${i}-${j}`}
                          dangerouslySetInnerHTML={{ __html: secondLine[1] }}
                        ></li>

                        {school.info && school.info[j].length > 0 && (
                          <li
                            className="remove-bullets"
                            key={`school-info-${i}-${j}`}
                          >
                            <ul
                              className="more-info-wrapper"
                              key={`school-info-wrapper-${i}-${j}`}
                            >
                              {school.info[j].map((info, k) => {
                                return (
                                  <li
                                    className="more-info"
                                    key={`school-info-item-${i}-${j}-${k}`}
                                    dangerouslySetInnerHTML={{ __html: info }}
                                  ></li>
                                );
                              })}
                            </ul>
                          </li>
                        )}
                      </Fragment>
                    );
                  })}
                </ul>
              );
            })}

          <br />
          <hr />

          <h2>Technical Skills</h2>
          <ul>
            {skills &&
              skills.map((skill, i) => {
                return (
                  <li className="skill-wrapper" key={`skill-wrapper-${i}`}>
                    {skill.mainItem}
                    {skill.subItems.length > 0 && (
                      <ul key={`skill-list-${i}`}>
                        {skill.subItems.map((subItem, j) => {
                          return (
                            <li key={`skill-subItem-${i}-${j}`}>{subItem}</li>
                          );
                        })}
                      </ul>
                    )}
                  </li>
                );
              })}
          </ul>

          <a className="subtle fancytxt" href={RESUME_PDF_URL}>
            View or download the PDF version of my résumé
          </a>
        </div>
      )}
    </div>
  );
};

export default ResumePage;

// web/src/components/ResumePage.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">Résumé</div>

    <div class="content-text">
      <h2 class="top">Experience</h2>
      <template v-for="job in experience">
        <ul :key="job.id" class="italic-spacer">
          <li class="left-column company">
            <a class="fancytxt" :href="job.url" v-html="job.firstLine[0]"></a>
          </li>
          <li class="right-column location" v-html="job.firstLine[1]"></li>
          <template v-for="(secondLine, i) in job.secondLine">
            <li
              class="left-column sub-left-column job-title"
              :class="{
                'same-company-spacing': i > 0 && job.info[i - 1].length > 0,
              }"
              :key="secondLine.id"
              v-html="secondLine[0]"
            ></li>
            <li
              class="right-column tenure"
              :class="{
                'same-company-spacing': i > 0 && job.info[i - 1].length > 0,
              }"
              :key="secondLine.id"
              v-html="secondLine[1]"
            ></li>
            <li
              class="remove-bullets"
              v-if="job.info[i].length > 0"
              :key="secondLine.id"
            >
              <ul class="more-info">
                <template v-for="info in job.info[i]">
                  <li class="more-info" :key="info.id" v-html="info"></li>
                </template>
              </ul>
            </li>
          </template>
        </ul>
      </template>

      <br />
      <hr />

      <h2>Education</h2>
      <template v-for="school in education">
        <ul :key="school.id" class="italic-spacer">
          <li class="left-column degree" v-html="school.firstLine[0]"></li>
          <li class="right-column location" v-html="school.firstLine[1]"></li>
          <template v-for="secondLine in school.secondLine">
            <li class="left-column sub-left-column school" :key="secondLine.id">
              <a class="fancytxt" :href="school.url" v-html="secondLine[0]"></a>
            </li>
            <li
              class="right-column tenure"
              :key="secondLine.id"
              v-html="secondLine[1]"
            ></li>
          </template>
        </ul>
      </template>

      <br />
      <hr />

      <h2>Technical Skills</h2>
      <ul ref="skills">
        <template v-for="skill in skills">
          <li class="skill-wrapper" :key="skill.id">
            {{ skill.mainItem }}
            <template v-if="skill.subItems.length > 0">
              <ul>
                <li :key="subItem.id" v-for="subItem in skill.subItems">
                  {{ subItem }}
                </li>
              </ul>
            </template>
          </li>
        </template>
      </ul>

      <a
        class="subtle fancytxt"
        href="https://github.com/chrismeyers/chrismeyers.info/blob/main/resume/LaTeX/Meyers_Chris/Meyers_Chris_Resume.pdf"
      >
        View or download the PDF version of my résumé
      </a>
    </div>
  </div>
</template>

<script>
import ResumeAPI from '@/utils/api/resume';
import ErrorsMixin from '@/mixins/Errors';

export default {
  name: 'resume-page',
  mixins: [ErrorsMixin],
  data() {
    return {
      experience: [],
      education: [],
      skills: [],
    };
  },
  async beforeRouteEnter(to, from, next) {
    try {
      const resume = await ResumeAPI.get();
      next((vm) => vm.setData({ resume }));
    } catch (error) {
      next((vm) => vm.setData({ error }));
    }
  },
  methods: {
    setData({ resume = null, error = null }) {
      if (error) {
        this.handleCommonErrors(error);
      } else {
        this.experience = resume.data.experience;
        this.education = resume.data.education;
        this.skills = resume.data.skills;
      }
    },
  },
};
</script>

<style scoped>
.remove-bullets {
  list-style-type: none;
}

@media screen and (min-width: 912px) {
  ul {
    overflow: hidden;
  }
  ul.italic-spacer {
    padding-right: 5px;
  }
  ul.more-info {
    padding-top: 10px;
  }

  .left-column {
    width: 70%;
    float: left;
  }

  .sub-left-column {
    list-style-type: none;
  }

  .right-column {
    float: right;
    width: 30%;
    text-align: right;
    list-style-type: none;
  }

  .company,
  .degree,
  .location {
    font-weight: bold;
  }

  .school,
  .job-title,
  .tenure {
    font-style: italic;
  }

  .same-company-spacing {
    margin-top: 20px;
  }
}

@media screen and (max-width: 911px) {
  .location,
  .school,
  .job-title,
  .tenure {
    list-style-type: none;
  }

  .company,
  .degree,
  .location {
    font-weight: bold;
  }

  .school,
  .job-title,
  .tenure {
    font-style: italic;
  }

  .job-title.same-company-spacing {
    margin-top: 15px;
  }
}
</style>
