// src/pages/Resume.jsx
import { Fragment } from 'react';
import { full as resume } from '../assets/generated/resume';
import { RESUME_PDF_URL, DEFAULT_DOCUMENT_TITLE } from '../utils/constants';
import styles from '../styles/Resume.module.css';

const Resume = () => {
  document.title = `Résumé | ${DEFAULT_DOCUMENT_TITLE}`;

  return (
    <div className="content">
      <div className="section-header section-header-size">
        <div>Résumé</div>
      </div>

      <div className="content-text">
        <h2 className="top">Experience</h2>
        {resume?.experience?.map((job) => (
          <ul
            className={styles.italicSpacer}
            key={`job-${job.firstLine[0]}-${job.secondLine[0][1]}`} // prettier-ignore
          >
            <li className={`${styles.leftColumn} ${styles.company}`}>
              <a className="fancytxt" href={job.url}>
                {job.firstLine[0]}
              </a>
            </li>
            <li className={`${styles.rightColumn} ${styles.location}`}>
              {job.firstLine[1]}
            </li>

            {job.secondLine.map((secondLine, j) => (
              <Fragment key={`job-secondLine-${secondLine[0]}`}>
                <li
                  className={`${styles.leftColumn} ${styles.subLeftColumn} ${
                    styles.jobTitle
                  } ${
                    j > 0 && job.info[j].length > 0
                      ? styles.sameCompanySpacing
                      : ''
                  }`}
                >
                  {secondLine[0]}
                </li>
                <li
                  className={`${styles.rightColumn} ${styles.tenure} ${
                    j > 0 && job.info[j].length > 0
                      ? styles.sameCompanySpacing
                      : ''
                  }`}
                  dangerouslySetInnerHTML={{ __html: secondLine[1] }} // eslint-disable-line react/no-danger
                />

                {job.info && job.info[j].length > 0 && (
                  <li className={styles.removeBullets}>
                    <ul className={styles.moreInfoWrapper}>
                      {job.info[j].map((info) => (
                        <li
                          className="more-info"
                          key={`job-info-item-${info}`}
                          dangerouslySetInnerHTML={{ __html: info }} // eslint-disable-line react/no-danger
                        />
                      ))}
                    </ul>
                  </li>
                )}
              </Fragment>
            ))}
          </ul>
        ))}

        <br />
        <hr />

        <h2>Education</h2>
        {resume?.education?.map((school) => (
          <ul
            className={styles.italicSpacer}
            key={`school-${school.firstLine[0]}`}
          >
            <li className={`${styles.leftColumn} ${styles.degree}`}>
              {school.firstLine[0]}
            </li>
            <li className={`${styles.rightColumn} ${styles.location}`}>
              {school.firstLine[1]}
            </li>
            {school.secondLine.map((secondLine, j) => (
              <Fragment key={`school-secondLine-${secondLine[0]}`}>
                <li
                  className={`${styles.leftColumn} ${styles.subLeftColumn} ${styles.school}`}
                >
                  <a className="fancytxt" href={school.url}>
                    {secondLine[0]}
                  </a>
                </li>
                <li
                  className={`${styles.rightColumn} ${styles.tenure}`}
                  dangerouslySetInnerHTML={{ __html: secondLine[1] }} // eslint-disable-line react/no-danger
                />

                {school.info && school.info[j].length > 0 && (
                  <li className={styles.removeBullets}>
                    <ul className={styles.moreInfoWrapper}>
                      {school.info[j].map((info) => (
                        <li
                          className="more-info"
                          key={`school-info-item-${info}`}
                        >
                          {info}
                        </li>
                      ))}
                    </ul>
                  </li>
                )}
              </Fragment>
            ))}
          </ul>
        ))}

        <br />
        <hr />

        <h2>Technical Skills</h2>
        <ul>
          {resume?.skills?.map((skill) => (
            <li
              className="skill-wrapper"
              key={`skill-wrapper-${skill.mainItem}`}
            >
              {skill.mainItem}
              {skill.subItems.length > 0 && (
                <ul>
                  {skill.subItems.map((subItem) => (
                    <li key={`skill-subItem-${subItem}`}>{subItem}</li>
                  ))}
                </ul>
              )}
            </li>
          ))}
        </ul>

        <a className="subtle fancytxt" href={RESUME_PDF_URL}>
          View or download the PDF version of my résumé
        </a>
      </div>
    </div>
  );
};

export default Resume;

// web/src/components/Resume.vue
<template>
  <div class="content">
    <div class="section-header section-header-size">Résumé</div>

    <div class="content-text">
      <h2 class="top">Experience</h2>
      <template v-for="job in experience">
        <ul :key="job.id" class="italic-spacer">
          <li class="left-column company" v-html="job.firstLine[0]"></li>
          <li class="right-column location" v-html="job.firstLine[1]"></li>
          <template v-for="(secondLine, i) in job.secondLine">
            <li class="left-column sub-left-column job-title" :class="{ 'same-company-spacing': i > 0 && job.info[i - 1].length > 0 }" :key="secondLine.id" v-html="secondLine[0]"></li>
            <li class="right-column tenure" :class="{ 'same-company-spacing': i > 0 && job.info[i - 1].length > 0 }" :key="secondLine.id" v-html="secondLine[1]"></li>
            <li class="remove-bullets" v-if="job.info[i].length > 0" :key="secondLine.id">
              <ul class="more-info">
                <template v-for="info in job.info[i]">
                  <li class="more-info" :key="info.id" v-html="info"></li>
                </template>
              </ul>
            </li>
          </template>
        </ul>
      </template>

      <br /> <hr>

      <h2>Education</h2>
      <template v-for="school in education">
        <ul :key="school.id" class="italic-spacer">
            <li class="left-column school" v-html="school.firstLine[0]"></li>
            <li class="right-column location" v-html="school.firstLine[1]"></li>
            <template v-for="secondLine in school.secondLine">
              <li class="left-column sub-left-column degree" :key="secondLine.id" v-html="secondLine[0]"></li>
              <li class="right-column tenure" :key="secondLine.id" v-html="secondLine[1]"></li>
            </template>
        </ul>
      </template>

      <br /> <hr>

      <h2>Technical Skills</h2>
      <ul>
        <template v-for="skill in skills">
          <li :key="skill.id">{{ skill.mainItem }}
            <template v-if="skill.subItems.length > 0">
              <ul>
                <li :key="subItem.id" v-for="subItem in skill.subItems">{{ subItem }}</li>
              </ul>
            </template>
          </li>
        </template>
      </ul>

      <a class="faded" href="https://github.com/chrismeyers/chrismeyers.info/blob/master/resume/LaTeX/Meyers_Chris/Meyers_Chris_Resume.pdf" target="_blank">
        View or download the PDF version of my résumé
      </a>
    </div>
  </div>
</template>

<script>
import ResumeAPI from "@/utils/api/resume"
import ConnectionError from "@/utils/errors/types/connection"
import ModalsMixin from "@/mixins/Modals"

export default {
  name: "Resume",
  mixins: [ModalsMixin],
  data () {
    return {
      experience: [],
      education: [],
      skills: []
    }
  },
  beforeRouteEnter (to, from, next) {
    ResumeAPI.get().then(
      resume => {
        next(vm => vm.setData(resume))
      }
    )
  },
  methods: {
    setData (resume) {
      if (resume instanceof ConnectionError) {
        this.showDialog(resume.title, resume.message)
      } else if (resume.status === 200) {
        this.experience = resume.data.experience
        this.education = resume.data.education
        this.skills = resume.data.skills
      } else {
        this.showDialog(resume.statusText, resume.data.error)
      }
    }
  }
}
</script>

<style scoped>
.remove-bullets {
  list-style-type: none;
}

@media screen and (min-width: 912px) {
  ul {
    overflow: hidden;
  }
  ul.italic-spacer {
    padding-right: 5px;
  }
  ul.more-info {
    padding-top: 10px;
  }

  .left-column {
    width: 70%;
    float: left;
  }

  .sub-left-column {
    list-style-type: none;
  }

  .right-column {
    float: right;
    width: 30%;
    text-align: right;
    list-style-type: none;
  }

  .company, .school, .location {
    font-weight: bold;
  }

  .degree, .job-title, .tenure {
    font-style: italic;
  }

  .same-company-spacing {
    margin-top: 20px;
  }
}

@media screen and (max-width: 911px) {
  .company, .school {
    font-weight: bold;
  }

  .location, .degree {
    font-weight: normal;
  }

  .location, .degree, .job-title, .tenure {
    list-style-type: none;
  }
  .location:before, .degree:before, .job-title:before, .tenure:before {
    content: "- ";
  }
}
</style>
